### PR TITLE
Request bullet point summary instead of two sentences

### PR DESCRIPTION
**Pull request by AGarrow**
## Context: why this PR?

I think that the summary ought to be bullet points.

If someone is making a 600 line change, 2 sentences aren't really helpful for me, what _is_ helpful is a list of bullet points like

- Move x service into y app
- refactor model z
- say hello to my mother
- add unique constraint
- ...

## Summary: what does this PR do?

- change the template

## Concerns: potential risks of this PR?

still seeing inadequate PR summaries

## Checks:
- [ ] This PR includes appropriate tests.
- [x] This PR is ready to deploy.
- This PR has risk:
    - [x] Risk 1 🤙
    - [ ] Risk 2 🐒
    - [ ] Risk 3+ 😱

## What's next:

pls write meaningful summaries lol

**Benebots Go!** ❤️‍🔥🍳🚀

### CODE REVIEW

**Comment by rodolfolottin** [comment]
I'm also in favor of that!

**Comment by markbenepass** [comment]
Super I'm on board

**Comment by rodolfolottin** [comment]
Should we merge it?

**Comment by markbenepass** [comment]
Yeah I think so!

**Pull request merged**
